- name: Salvar alterações
      run: |
        git config --global user.name "Robo Rei da Rodada"
        git config --global user.email "robo@reidarodada.com"
        git add app.py jogos_status.json || echo "Sem arquivos"
        git commit -m "🤖 Atualização de cores e resultados" || echo "Sem mudanças"
        git push
